Word Embedding

Embedding.ipynb

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your health is good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your health is good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
## One hot representation for every word
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5771, 2149, 4110, 9090],
 [5771, 2149, 4110, 2217],
 [5771, 2947, 4110, 7451],
 [5608, 6018, 5801, 4991, 1522],
 [5608, 6018, 5801, 4991, 6993],
 [9444, 5771, 9508, 4110, 1950],
 [3051, 3269, 5146, 4991]]

In [6]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5771 2149 4110 9090]
 [   0    0    0    0 5771 2149 4110 2217]
 [   0    0    0    0 5771 2947 4110 7451]
 [   0    0    0 5608 6018 5801 4991 1522]
 [   0    0    0 5608 6018 5801 4991 6993]
 [   0    0    0 9444 5771 9508 4110 1950]
 [   0    0    0    0 3051 3269 5146 4991]]


In [9]:
#Feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 232ms/step


array([[[-0.03132184,  0.03940845,  0.00817318, -0.04941361,
         -0.03329904,  0.0078794 , -0.00833891, -0.02597065,
         -0.03400198, -0.01182304],
        [-0.03132184,  0.03940845,  0.00817318, -0.04941361,
         -0.03329904,  0.0078794 , -0.00833891, -0.02597065,
         -0.03400198, -0.01182304],
        [-0.03132184,  0.03940845,  0.00817318, -0.04941361,
         -0.03329904,  0.0078794 , -0.00833891, -0.02597065,
         -0.03400198, -0.01182304],
        [-0.03132184,  0.03940845,  0.00817318, -0.04941361,
         -0.03329904,  0.0078794 , -0.00833891, -0.02597065,
         -0.03400198, -0.01182304],
        [-0.03919458, -0.01814525,  0.04271127, -0.0289541 ,
          0.02210318,  0.03316395,  0.00321829,  0.04594679,
         -0.04650036,  0.02293353],
        [ 0.01314571, -0.01312839,  0.00024978,  0.01739101,
          0.03905082,  0.02499411, -0.0499251 , -0.00828799,
         -0.04628808, -0.02943303],
        [ 0.0355945 , -0.03879308,  0.04533397, -0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5771, 2149, 4110, 9090], dtype=int32)

**End to end DL project with Simple RNN**

In [14]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

In [15]:
## Load the IMDB Dataset

max_features=10000 # vocabulary size
(X_train,y_train),(X_test,y_test)=imdb.load_data(num_words=max_features)

# print the shape of data
print(f'Training data shape: {X_train.shape}, Training labels shape : {y_train.shape}')
print(f'Testing data shape: {X_test.shape}, Testing labels shape : {y_test.shape}')

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
Training data shape: (25000,), Training labels shape : (25000,)
Testing data shape: (25000,), Testing labels shape : (25000,)


In [16]:
X_train[0],y_train[0]

([1,
  14,
  22,
  16,
  43,
  530,
  973,
  1622,
  1385,
  65,
  458,
  4468,
  66,
  3941,
  4,
  173,
  36,
  256,
  5,
  25,
  100,
  43,
  838,
  112,
  50,
  670,
  2,
  9,
  35,
  480,
  284,
  5,
  150,
  4,
  172,
  112,
  167,
  2,
  336,
  385,
  39,
  4,
  172,
  4536,
  1111,
  17,
  546,
  38,
  13,
  447,
  4,
  192,
  50,
  16,
  6,
  147,
  2025,
  19,
  14,
  22,
  4,
  1920,
  4613,
  469,
  4,
  22,
  71,
  87,
  12,
  16,
  43,
  530,
  38,
  76,
  15,
  13,
  1247,
  4,
  22,
  17,
  515,
  17,
  12,
  16,
  626,
  18,
  2,
  5,
  62,
  386,
  12,
  8,
  316,
  8,
  106,
  5,
  4,
  2223,
  5244,
  16,
  480,
  66,
  3785,
  33,
  4,
  130,
  12,
  16,
  38,
  619,
  5,
  25,
  124,
  51,
  36,
  135,
  48,
  25,
  1415,
  33,
  6,
  22,
  12,
  215,
  28,
  77,
  52,
  5,
  14,
  407,
  16,
  82,
  2,
  8,
  4,
  107,
  117,
  5952,
  15,
  256,
  4,
  2,
  7,
  3766,
  5,
  723,
  36,
  71,
  43,
  530,
  476,
  26,
  400,
  317,
  46,
  7,
  4,
  2,
  1029,
  

In [17]:
# Inspect a sample review and it's label
sample_review=X_train[0]
sample_label=y_train[0]

print(f'Sample review (as integers) : {sample_review}')
print(f'Sample label : {sample_label}')

Sample review (as integers) : [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
Sample label : 1


In [18]:
#Mappin of words index back to words(for understanding)
word_index=imdb.get_word_index()
word_index
reverse_word_index= {value : key for key, value in word_index.items()}
reverse_word_index

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 1s 1us/step


{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [19]:
decoded_review= ' '.join([reverse_word_index.get(i - 3, '?') for i in sample_review])
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [20]:
from tensorflow.keras.preprocessing import sequence

max_len=500

X_train=sequence.pad_sequences(X_train,maxlen=max_len)
X_test=sequence.pad_sequences(X_test,maxlen=max_len)
X_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [21]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [22]:
## Train our Simple RNN
model=Sequential()
# Feature representation dimensions=128 we taken as our dataset is big
model.add(Embedding(max_features,128,input_length=max_len)) # Embeding layers
model.add(SimpleRNN(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [25]:
# Create an instance of early stopping call backcall
from tensorflow.keras.callbacks import EarlyStopping
earlystopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)
earlystopping

In [26]:
## Train the mmodel with early stopping
model.fit(X_train,y_train,epochs=10,batch_size=32,validation_split=0.2,callbacks=[earlystopping])

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 147s 231ms/step - accuracy: 0.5825 - loss: 81153.1328 - val_accuracy: 0.6150 - val_loss: 0.6334
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 203s 233ms/step - accuracy: 0.6906 - loss: 0.6133 - val_accuracy: 0.6178 - val_loss: 0.6398
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 147s 235ms/step - accuracy: 0.7431 - loss: 0.5473 - val_accuracy: 0.6640 - val_loss: 0.5911
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 203s 236ms/step - accuracy: 0.7092 - loss: nan - val_accuracy: 0.5062 - val_loss: nan
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 200s 232ms/step - accuracy: 0.4964 - loss: nan - val_accuracy: 0.5062 - val_loss: nan
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 206s 239ms/step - accuracy: 0.4983 - loss: nan - val_accuracy: 0.5062 - val_loss: nan
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 145s 232ms/step - accuracy: 0.4940 - loss: nan - val_accuracy: 0.5062 - val_loss: nan
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 145s 233ms/step - accuracy: 0.4975 - loss: nan - val_acc

In [27]:
## save model file
model.save('simple_rnn_imdb.h5')

In [28]:
# prdiction.ipynb
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import load_model

In [29]:
# load the imdb dataset word index
word_index=imdb.get_word_index()
reverse_word_index={value: key for key , value in word_index.items()}

In [30]:
# load the pretrained model with relu activation
model=load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (32, 500, 128)              │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ (32, 128)                   │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (32, 1)                     │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [31]:
model.get_weights()

[array([[-4.7799262e-01,  4.4425473e-01,  4.1177297e-01, ...,
          4.7934929e-01,  4.2185366e-01,  3.8355172e-01],
        [-2.2954740e-02,  4.4936892e-02,  3.1419940e-02, ...,
         -2.0493988e-02,  7.6383263e-02, -2.4218347e-02],
        [ 2.5854921e-02,  8.7319158e-02, -7.7302023e-03, ...,
          8.1833795e-02,  4.2166341e-02,  2.9727623e-02],
        ...,
        [-3.9962964e-04, -4.0743042e-02, -3.0588057e-02, ...,
          2.1361388e-02,  2.0390101e-02, -1.1232401e-02],
        [ 6.1649079e-03,  3.5020445e-02, -8.0791213e-02, ...,
         -2.5118619e-02,  5.0860923e-03,  5.0391577e-02],
        [-1.0012327e-01, -9.1379575e-02, -4.2658124e-02, ...,
         -1.1333936e-01,  4.3329384e-02, -9.3523666e-02]], dtype=float32),
 array([[-0.08934001, -0.06169415, -0.09107271, ...,  0.04207271,
          0.05738296,  0.1417841 ],
        [-0.05839463,  0.05460003, -0.09849453, ...,  0.08368973,
          0.05123299,  0.02097177],
        [ 0.02624502,  0.02372304, -0.14433779

In [32]:
# Step 2 Helper Function
# function to decode reviews
def decode_review(encoded_review):
  return ' '.join([reverse_word_index.get(i - 3, '?') for i in encoded_review])

#Function to preprocess user input
def preprocess_text(text):
  words=text.lower().split()
  encoded_review=[word_index.get(word,2) + 3 for word in words]
  padded_review=sequence.pad_sequences([encoded_review],maxlen=500)
  return padded_review

In [33]:
## Prediction Function
def predict_sentiment(review):
  preproceseed_input=preprocess_text(review)

  prediction=model.predict(preproceseed_input)

  sentiment= 'Positive' if prediction[0][0] > 0.5 else 'Negative'

  return sentiment, prediction[0][0]

In [34]:
# step 4 :- User input and prediction
#example review for prediction
example_review='This movie was fantastic! The acting was great and the plot was thrilling.'

sentiment,score=predict_sentiment(example_review)

print(f'Review : {example_review}')
print(f'Sentiment : {sentiment}')
print(f'Prediction score : {score}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step
Review : This movie was fantastic! The acting was great and the plot was thrilling.
Sentiment : Negative
Prediction score : 0.006209935061633587
