Word Embedding

Embedding.ipynb

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
## Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your health is good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your health is good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
## One hot representation for every word
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1404, 9383, 5472, 6860],
 [1404, 9383, 5472, 7898],
 [1404, 6438, 5472, 5937],
 [1120, 8206, 404, 3295, 7846],
 [1120, 8206, 404, 3295, 4269],
 [8394, 1404, 343, 5472, 3030],
 [5762, 7816, 9820, 3295]]

In [7]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1404 9383 5472 6860]
 [   0    0    0    0 1404 9383 5472 7898]
 [   0    0    0    0 1404 6438 5472 5937]
 [   0    0    0 1120 8206  404 3295 7846]
 [   0    0    0 1120 8206  404 3295 4269]
 [   0    0    0 8394 1404  343 5472 3030]
 [   0    0    0    0 5762 7816 9820 3295]]


In [10]:
#Feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step


array([[[ 0.02646026,  0.01281967,  0.03226331,  0.03313876,
          0.01709067, -0.02109617,  0.01845534,  0.00836947,
         -0.02758033, -0.00267068],
        [ 0.02646026,  0.01281967,  0.03226331,  0.03313876,
          0.01709067, -0.02109617,  0.01845534,  0.00836947,
         -0.02758033, -0.00267068],
        [ 0.02646026,  0.01281967,  0.03226331,  0.03313876,
          0.01709067, -0.02109617,  0.01845534,  0.00836947,
         -0.02758033, -0.00267068],
        [ 0.02646026,  0.01281967,  0.03226331,  0.03313876,
          0.01709067, -0.02109617,  0.01845534,  0.00836947,
         -0.02758033, -0.00267068],
        [-0.0213981 ,  0.04520601,  0.04399427, -0.04818806,
         -0.01655736, -0.03544904,  0.02236592, -0.01081378,
         -0.02183552, -0.02804511],
        [-0.02798542, -0.02354494,  0.00742956,  0.0455637 ,
         -0.0002737 ,  0.04357047, -0.04469417, -0.01977613,
         -0.04299939, -0.01013579],
        [-0.02889723,  0.04261513,  0.00986449, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 1404, 9383, 5472, 6860], dtype=int32)

**End to end DL project with Simple RNN**

In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

In [16]:
## Load the IMDB Dataset

max_features=10000 # vocabulary size
(X_train,y_train),(X_test,y_test)=imdb.load_data(num_words=max_features)

# print the shape of data
print(f'Training data shape: {X_train.shape}, Training labels shape : {y_train.shape}')
print(f'Testing data shape: {X_test.shape}, Testing labels shape : {y_test.shape}')

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Training data shape: (25000,), Training labels shape : (25000,)
Testing data shape: (25000,), Testing labels shape : (25000,)


In [17]:
X_train[0],y_train[0]

([1,
  14,
  22,
  16,
  43,
  530,
  973,
  1622,
  1385,
  65,
  458,
  4468,
  66,
  3941,
  4,
  173,
  36,
  256,
  5,
  25,
  100,
  43,
  838,
  112,
  50,
  670,
  2,
  9,
  35,
  480,
  284,
  5,
  150,
  4,
  172,
  112,
  167,
  2,
  336,
  385,
  39,
  4,
  172,
  4536,
  1111,
  17,
  546,
  38,
  13,
  447,
  4,
  192,
  50,
  16,
  6,
  147,
  2025,
  19,
  14,
  22,
  4,
  1920,
  4613,
  469,
  4,
  22,
  71,
  87,
  12,
  16,
  43,
  530,
  38,
  76,
  15,
  13,
  1247,
  4,
  22,
  17,
  515,
  17,
  12,
  16,
  626,
  18,
  2,
  5,
  62,
  386,
  12,
  8,
  316,
  8,
  106,
  5,
  4,
  2223,
  5244,
  16,
  480,
  66,
  3785,
  33,
  4,
  130,
  12,
  16,
  38,
  619,
  5,
  25,
  124,
  51,
  36,
  135,
  48,
  25,
  1415,
  33,
  6,
  22,
  12,
  215,
  28,
  77,
  52,
  5,
  14,
  407,
  16,
  82,
  2,
  8,
  4,
  107,
  117,
  5952,
  15,
  256,
  4,
  2,
  7,
  3766,
  5,
  723,
  36,
  71,
  43,
  530,
  476,
  26,
  400,
  317,
  46,
  7,
  4,
  2,
  1029,
  

In [18]:
# Inspect a sample review and it's label
sample_review=X_train[0]
sample_label=y_train[0]

print(f'Sample review (as integers) : {sample_review}')
print(f'Sample label : {sample_label}')

Sample review (as integers) : [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
Sample label : 1


In [19]:
#Mappin of words index back to words(for understanding)
word_index=imdb.get_word_index()
word_index
reverse_word_index= {value : key for key, value in word_index.items()}
reverse_word_index

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [20]:
decoded_review= ' '.join([reverse_word_index.get(i - 3, '?') for i in sample_review])
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [21]:
from tensorflow.keras.preprocessing import sequence

max_len=500

X_train=sequence.pad_sequences(X_train,maxlen=max_len)
X_test=sequence.pad_sequences(X_test,maxlen=max_len)
X_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [22]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [23]:
## Train our Simple RNN
model=Sequential()
# Feature representation dimensions=128 we taken as our dataset is big
model.add(Embedding(max_features,128,input_length=max_len)) # Embeding layers
model.add(SimpleRNN(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [26]:
# Create an instance of early stopping call backcall
from tensorflow.keras.callbacks import EarlyStopping
earlystopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)
earlystopping

In [27]:
## Train the mmodel with early stopping
model.fit(X_train,y_train,epochs=10,batch_size=32,validation_split=0.2,callbacks=[earlystopping])

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 155s 244ms/step - accuracy: 0.5602 - loss: 5153.9824 - val_accuracy: 0.5984 - val_loss: 0.6617
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 150s 240ms/step - accuracy: 0.6633 - loss: 5.0919 - val_accuracy: 0.6350 - val_loss: 0.6211
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 204s 243ms/step - accuracy: 0.7351 - loss: 0.5378 - val_accuracy: 0.7302 - val_loss: 0.5292
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 151s 242ms/step - accuracy: 0.8297 - loss: 0.4051 - val_accuracy: 0.7798 - val_loss: 0.4708
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 204s 246ms/step - accuracy: 0.8745 - loss: 0.3010 - val_accuracy: 0.7716 - val_loss: 0.4908
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 200s 243ms/step - accuracy: 0.9132 - loss: 0.2333 - val_accuracy: 0.8122 - val_loss: 0.4654
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 201s 241ms/step - accuracy: 0.8382 - loss: 0.3905 - val_accuracy: 0.8082 - val_loss: 0.4839
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 204s 244ms/step - accuracy: 0.941

In [28]:
## save model file
model.save('simple_rnn_imdb.h5')

In [29]:
# prdiction.ipynb
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import load_model

In [30]:
# load the imdb dataset word index
word_index=imdb.get_word_index()
reverse_word_index={value: key for key , value in word_index.items()}

In [31]:
# load the pretrained model with relu activation
model=load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (32, 500, 128)              │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ (32, 128)                   │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (32, 1)                     │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [32]:
model.get_weights()

[array([[ 0.05904543, -0.08319171, -0.06140236, ...,  0.11007243,
         -0.01877811, -0.12541048],
        [-0.0906449 , -0.00793815,  0.04789525, ..., -0.02904264,
         -0.00560727, -0.01222532],
        [-0.12829839,  0.10753977, -0.03699538, ..., -0.06895234,
          0.00887247,  0.15954043],
        ...,
        [ 0.14169423, -0.12068132, -0.08153153, ...,  0.12056713,
          0.04779708, -0.16940191],
        [-0.07993961, -0.1082164 ,  0.05990629, ..., -0.06059893,
         -0.04322733,  0.02996401],
        [ 0.16807991,  0.07127607, -0.03711366, ...,  0.15163402,
          0.16083112, -0.15402445]], dtype=float32),
 array([[ 0.08880959, -0.07670731, -0.00153941, ..., -0.01353471,
          0.08414402,  0.06304327],
        [ 0.08500733, -0.09132103,  0.08355312, ..., -0.12164538,
          0.09354112, -0.03699722],
        [-0.01788693,  0.09969223, -0.04997744, ...,  0.13665253,
         -0.07086354, -0.05099045],
        ...,
        [ 0.07483798, -0.03741294,  0.0

In [33]:
# Step 2 Helper Function
# function to decode reviews
def decode_review(encoded_review):
  return ' '.join([reverse_word_index.get(i - 3, '?') for i in encoded_review])

#Function to preprocess user input
def preprocess_text(text):
  words=text.lower().split()
  encoded_review=[word_index.get(word,2) + 3 for word in words]
  padded_review=sequence.pad_sequences([encoded_review],maxlen=500)
  return padded_review

In [34]:
## Prediction Function
def predict_sentiment(review):
  preproceseed_input=preprocess_text(review)

  prediction=model.predict(preproceseed_input)

  sentiment= 'Positive' if prediction[0][0] > 0.5 else 'Negative'

  return sentiment, prediction[0][0]

In [35]:
# step 4 :- User input and prediction
#example review for prediction
example_review='This movie was fantastic! The acting was great and the plot was thrilling.'

sentiment,score=predict_sentiment(example_review)

print(f'Review : {example_review}')
print(f'Sentiment : {sentiment}')
print(f'Prediction score : {score}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step
Review : This movie was fantastic! The acting was great and the plot was thrilling.
Sentiment : Positive
Prediction score : 0.8699265122413635
